=== samirm-git/hajjscanner/schema/hajjPackage.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "hajjPackage.json",
  "title": "Package",
  "description": "Hajj package details",
  "type": "object",
  "properties": {
    "company":{
    "description": "company name",
    "type": "string"
    },
    "url":{
      "description": "url to package details",
      "type": "string",
      "format": "uri"
    },
    "ppp" : {
      "description": "price per person in £", 
      "type": ["integer", "null"],
      "minimum": 2000,
      "maximum": 25000,
      "minItems": 1
      },
    "year":{
      "description": "year in which package is offered",
      "type": ["integer", "null"],
      "minimum": 2020
    },
    "total_days":{
      "description": "total number of days in package",
      "type": ["integer", "null"],
      "minimum": 10,
      "maximum": 30
    },
    "tier":{
      "description": "type of hajj package: luxury, premium, or economy",
      "type": ["string", "null"],
      "enum": ["luxury", "premium", "economy", null]
    },
    "stars":{
      "description": "star rating (1-5)",
      "type": ["integer", "null"],
      "minimum": 1,
      "maximum": 5
    },
    "is_shifting":{
      "description": "True if shifting package, False if non shifting",
      "type": ["boolean", "null"]
    },
    "departure_city":{
      "description": "The deparature city where the umrah is being offered from.",
      "type": ["string", "null"]
    },
    "is_visa_included":{
      "description": "True if visa included in package, False if visa not included",
      "type": ["boolean", "null"]
    },

    "makkah_hotel": {
      "description": "Makkah hotel details",
      "$ref": "hotel.json"
    },
    "madinah_hotel":{
      "description": "Madinah hotel details",
      "$ref": "hotel.json"
    }
  },
  "required": ["company","ppp", "year", "total_days", "stars", "is_shifting", "departure_city", "is_visa_included", "makkah_hotel", "madinah_hotel"]
}

=== samirm-git/hajjscanner/tests/data/alhaqtravel/hajj/expected.json
{
    "url": "https://www.alhaqtravel.co.uk/book/hajj-package-for-21-nights-all-inclusive-with-flight-from-manchester/",
    "company": "alhaqtravel",
    "ppp": 7986,
    "year": null,
    "total_days": 21,
    "tier": "luxury",
    "stars": null,
    "departure_city": "Manchester",
    "is_visa_included": true,
    "is_shifting": false,
    "makkah_hotel": {
        "total_days": 14,
        "name": "Meridien Towers Makkah",
        "images": [
            "https://www.alhaqtravel.co.uk/media/hotels/20313067.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/20313172.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/20313056.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/20313158.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/20313163.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/327931616.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/20313094.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/20313167.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/7389472.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/7389442.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/20313161.jpg"
        ],
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 7,
        "name": "Al-Aqeeq Al-Madinah Hotel",
        "images": [
            "https://www.alhaqtravel.co.uk/media/hotels/522052948.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/522054746.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/5220521461.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/522058600.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/522055140.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/522052148.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/522054710.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/522054738.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/3335278381.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/522052147.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/5220521471.jpg"
        ],
        "stars": null,
        "has_wifi": false,
        "has_ac": true,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/zamzamtravels/hajj/expected.json
{
    "url": "https://www.zamzamtravels.org.uk/hajj-packages-2022-uk/5-star-late-hajj-package-2022-uk-two-weeks-non-shifting",
    "company": "zamzamtravels",
    "ppp": null,
    "year": 2022,
    "total_days": null,
    "tier": "luxury",
    "stars": 5,
    "departure_city": "Birmingham",
    "is_visa_included": true,
    "is_shifting": false,
    "makkah_hotel": {
        "total_days": 15,
        "name": "Elaf Kinda Hotel",
        "images": [
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/elaf-kinda/68828349.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/elaf-kinda/68828377.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/elaf-kinda/68828388.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/elaf-kinda/68828356.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/elaf-kinda/68828365.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/elaf-kinda/68828374.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/elaf-kinda/68828386.jpg"
        ],
        "stars": 5,
        "has_wifi": true,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": null,
        "name": "Anwar Al-Madinah Movenpick Hotel",
        "images": [
            "https://cdn.zamzamtravels.org.uk/images/hotels/medinah/shaza-al-madina/45329372.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/medinah/shaza-al-madina/45331151.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/medinah/shaza-al-madina/45331319.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/medinah/shaza-al-madina/19731927.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/medinah/shaza-al-madina/45329391.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/medinah/shaza-al-madina/19731918.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/medinah/shaza-al-madina/19731930.jpg"
        ],
        "stars": 5,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/haramainhajjtours/hajj/ideal.json
{
    "url": "https://haramainhajjtours.co.uk/blog/packages/hajj-2026-14-days-test-package/",
    "company": "haramainhajjtours",
    "ppp": null,
    "year": 2026,
    "total_days": 14,
    "tier": "luxury",
    "stars": 5,
    "departure_city": "Manchester",
    "is_visa_included": true,
    "is_shifting": false,
    "makkah_hotel": {
        "total_days": 5,
        "name": "Makkah Towers",
        "images": null,
        "stars": 5,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 3,
        "name": "Dar Al-Eiman Al-Haram Hotel",
        "images": null,
        "stars": 4,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/kiswahtravels/hajj/ideal.json
{
    "url": "https://kiswahtravels.co.uk/hajj-packages/",
    "company": "kiswahtravels",
    "ppp": 7685,
    "year": 2027,
    "total_days": null,
    "tier": "luxury",
    "stars": 3,
    "departure_city": null,
    "is_visa_included": true,
    "is_shifting": null,
    "makkah_hotel": {
        "total_days": null,
        "name": "Tera Ajyad Hotel",
        "images": null,
        "stars": 3,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": 4
    },
    "madinah_hotel": {
        "total_days": null,
        "name": "Durrat Al-Madinah Hotel",
        "images": null,
        "stars": 3,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": 4
    }
}

=== samirm-git/hajjscanner/tests/data/eliteumrah/hajj/ideal.json
{
  "url": "https://eliteumrah.co.uk/14-days-economy-hajj-package/",
  "company": "eliteumrah",
  "ppp": 4685,
  "year": null,
  "total_days": 14,
  "tier": "economy",
  "stars": null,
  "departure_city": null,
  "is_visa_included": true,
  "is_shifting": true,
  "makkah_hotel": {
    "name": null,
    "total_days": 8,
    "images": null,
    "stars": null,
    "has_wifi": false,
    "has_ac": false,
    "other_amenities": "Breakfast included",
    "distance_to_haram": null,
    "walk_to_haram": null,
    "number_of_beds": null
  },
  "madinah_hotel": {
    "name": null,
    "total_days": 7,
    "images": null,
    "stars": null,
    "has_wifi": false,
    "has_ac": false,
    "other_amenities": "Breakfast included",
    "distance_to_haram": null,
    "walk_to_haram": null,
    "number_of_beds": null
  }
}

=== samirm-git/hajjscanner/tests/data/umrah-alamanah/hajj/expected.json
{
    "url": "https://umrah-alamanah.com/hajj-packages-2026/",
    "company": "umrah-alamanah",
    "ppp": 9250,
    "year": 2027,
    "total_days": 17,
    "tier": "economy",
    "stars": 5,
    "departure_city": null,
    "is_visa_included": true,
    "is_shifting": false,
    "makkah_hotel": {
        "total_days": 6,
        "name": null,
        "images": null,
        "stars": 5,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": 634,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 3,
        "name": null,
        "images": null,
        "stars": 5,
        "has_wifi": false,
        "has_ac": true,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/duatravels/hajj/expected.json
{
    "url": "https://www.linkedin.com/checkpoint/lg/login?session_redirect=https%3A%2F%2Fwww%2Elinkedin%2Ecom%2FshareArticle%3Fmini%3Dtrue%26url%3Dhttps%3A%2F%2Fduatravels%2Eco%2Euk%2Fa-brief-guide-to-hajj-and-hajj-packages%2F%26title%3DA%2BBrief%2BGuide%2Bto%2BHajj%2Band%2BHajj%2BPackages%2B2026&fromSignIn=true&trk=reset_password",
    "company": "duatravels",
    "ppp": null,
    "year": null,
    "total_days": null,
    "tier": null,
    "stars": null,
    "departure_city": null,
    "is_visa_included": false,
    "is_shifting": false,
    "makkah_hotel": null,
    "madinah_hotel": null
}

=== samirm-git/hajjscanner/tests/data/umrah-alamanah/hajj/ideal.json
{
    "url": "https://umrah-alamanah.com/hajj-packages-2026/",
    "company": "umrah-alamanah",
    "ppp": 9250,
    "year": 2027,
    "total_days": 17,
    "tier": null,
    "stars": 5,
    "departure_city": "London",
    "is_visa_included": true,
    "is_shifting": true,
    "makkah_hotel": {
        "total_days": 6,
        "name": "Swissotel Al Maqam Makkah",
        "images": [
            "https://umrah-alamanah.com/wp-content/uploads/elementor/thumbs/Swiss-Al-muqam-hajj-2026-from-Uk--rn7flovecw46milkq1gegrgmm5irj7lpk5y5ybzboc.png"
        ],
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": 4
    },
    "madinah_hotel": {
        "total_days": 3,
        "name": "Dar Al-Hijra InterContinental Hotel",
        "images": [
            "https://umrah-alamanah.com/wp-content/uploads/elementor/thumbs/dar-ul-Hijra-Madinah-rn7flovecw46milkq1gegrgmm5irj7lpk5y5ybzboc.png"
        ],
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": 120,
        "walk_to_haram": null,
        "number_of_beds": 4
    }
}
