=== samirm-git/hajjscanner/schema/hajjPackage.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "hajjPackage.json",
  "title": "Package",
  "description": "Hajj package details",
  "type": "object",
  "properties": {
    "company":{
    "description": "company name",
    "type": "string"
    },
    "url":{
      "description": "url to package details",
      "type": "string",
      "format": "uri"
    },
    "ppp" : {
      "description": "price per person in £", 
      "type": ["integer", "null"],
      "minimum": 2000,
      "maximum": 25000,
      "minItems": 1
      },
    "year":{
      "description": "year in which package is offered",
      "type": ["integer", "null"],
      "minimum": 2020
    },
    "total_days":{
      "description": "total number of days in package",
      "type": ["integer", "null"],
      "minimum": 10,
      "maximum": 30
    },
    "tier":{
      "description": "type of hajj package: luxury, premium, or economy",
      "type": ["string", "null"],
      "enum": ["luxury", "premium", "economy", null]
    },
    "stars":{
      "description": "star rating (1-5)",
      "type": ["integer", "null"],
      "minimum": 1,
      "maximum": 5
    },
    "is_shifting":{
      "description": "True if shifting package, False if non shifting",
      "type": ["boolean", "null"]
    },
    "departure_city":{
      "description": "The deparature city where the umrah is being offered from.",
      "type": ["string", "null"]
    },
    "is_visa_included":{
      "description": "True if visa included in package, False if visa not included",
      "type": ["boolean", "null"]
    },

    "makkah_hotel": {
      "description": "Makkah hotel details",
      "$ref": "hotel.json"
    },
    "madinah_hotel":{
      "description": "Madinah hotel details",
      "$ref": "hotel.json"
    }
  },
  "required": ["company","ppp", "year", "total_days", "stars", "is_shifting", "departure_city", "is_visa_included", "makkah_hotel", "madinah_hotel"]
}

=== samirm-git/hajjscanner/tests/data/alhayatourstravel/hajj/expected.json
{
    "url": "https://alhayatourstravel.com/india-hajj-packages/",
    "company": "alhayatourstravel",
    "ppp": null,
    "year": 2026,
    "total_days": null,
    "tier": null,
    "stars": null,
    "departure_city": null,
    "is_visa_included": false,
    "is_shifting": false,
    "makkah_hotel": null,
    "madinah_hotel": null
}

=== samirm-git/hajjscanner/tests/data/haramainhajjtours/hajj/expected.json
{
    "url": "https://haramainhajjtours.co.uk/blog/packages/hajj-2026-14-days-test-package/",
    "company": "haramainhajjtours",
    "ppp": null,
    "year": 2026,
    "total_days": 14,
    "tier": "luxury",
    "stars": 5,
    "departure_city": "Manchester",
    "is_visa_included": true,
    "is_shifting": false,
    "makkah_hotel": {
        "total_days": null,
        "name": "Al Bow Towers Hotel",
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": null,
        "name": "Dar Al-Eiman Al-Haram Hotel",
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/sarainternationaltravel/hajj/ideal.json
{
    "url": "https://sarainternationaltravel.com/nusuk-hajj-packages-for-france/",
    "company": "sarainternationaltravel",
    "ppp": 8170,
    "year": 2027,
    "total_days": null,
    "tier": null,
    "stars": 5,
    "departure_city": null,
    "is_visa_included": true,
    "is_shifting": null,
    "makkah_hotel": {
        "total_days": null,
        "name": null,
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": null,
        "name": null,
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/makkahtour/hajj/expected.json
{
    "url": "https://www.makkahtour.co.uk/blogs/get-the-cheapest-hajj-and-umrah-packages-from-uk-best-umrah-travel-agency/",
    "company": "makkahtour",
    "ppp": null,
    "year": null,
    "total_days": null,
    "tier": null,
    "stars": null,
    "departure_city": null,
    "is_visa_included": false,
    "is_shifting": true,
    "makkah_hotel": {
        "total_days": null,
        "name": null,
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": null
}

=== samirm-git/hajjscanner/tests/data/sarainternationaltravel/hajj/expected.json
{
    "url": "https://sarainternationaltravel.com/nusuk-hajj-packages-for-france/",
    "company": "sarainternationaltravel",
    "ppp": 8170,
    "year": 2027,
    "total_days": null,
    "tier": "luxury",
    "stars": 5,
    "departure_city": null,
    "is_visa_included": true,
    "is_shifting": false,
    "makkah_hotel": {
        "total_days": 14,
        "name": null,
        "images": [
            "https://sarainternationaltravel.com/wp-content/uploads/2026/06/Premium-Makkah-First.jpg-1024x682.webp",
            "https://sarainternationaltravel.com/wp-content/uploads/2025/09/Premium-2-Makkah-First.jpg-1024x682.webp",
            "https://sarainternationaltravel.com/wp-content/uploads/2026/06/Luxury-Makkah-First.jpg-1024x682.webp",
            "https://sarainternationaltravel.com/wp-content/uploads/2026/06/Luxury-Two-Bedroom-Makkah-First.jpg-1024x682.webp"
        ],
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 14,
        "name": null,
        "images": [
            "https://sarainternationaltravel.com/wp-content/uploads/2026/06/Luxury-Madinah-First.jpg-1024x682.webp",
            "https://sarainternationaltravel.com/wp-content/uploads/2025/10/WhatsApp-Image-2026-06-20-at-12.19.22-PM-1024x682.webp",
            "https://sarainternationaltravel.com/wp-content/uploads/2025/09/Premium-2-Madinah-First.jpg-1024x682.webp"
        ],
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/hajjumrahhub/hajj/expected.json
{
    "url": "https://www.hajjumrahhub.co.uk/hajj/2-3-weeks-non-shifting-hajj-package.html",
    "company": "hajjumrahhub",
    "ppp": 6999,
    "year": null,
    "total_days": null,
    "tier": null,
    "stars": 3,
    "departure_city": "Belfast",
    "is_visa_included": true,
    "is_shifting": false,
    "makkah_hotel": {
        "total_days": null,
        "name": null,
        "images": [
            "https://www.hajjumrahhub.co.uk/media/hotel/Al%20Saher%20Hotel1.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Al%20Saher%20Hotel8.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Al%20Saher%20Hotel14.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Al%20Saher%20Hotel3.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Al%20Saher%20Hotel4.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Al%20Saher%20Hotel13.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Al%20Saher%20Hotel6.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Al%20Saher%20Hotel12.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Al%20Saher%20Hotel11.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Al%20Saher%20Hotel5.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Al%20Saher%20Hotel10.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Al%20Saher%20Hotel2.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Al%20Saher%20Hotel9.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Al%20Saher%20Hotel.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Al%20Saher%20Hotel7.jpg"
        ],
        "stars": null,
        "has_wifi": true,
        "has_ac": true,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": null,
        "name": "Saja Al Madinah Hotel",
        "images": [
            "https://www.hajjumrahhub.co.uk/media/hotel/Saja%20AlMadinah%20Hotel3.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Saja%20AlMadinah%20Hotel4.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Saja%20AlMadinah%20Hotel6.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Saja%20AlMadinah%20Hotel9.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Saja%20AlMadinah%20Hotel7.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Saja%20AlMadinah%20Hotel12.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Saja%20AlMadinah%20Hotel8.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Saja%20AlMadinah%20Hotel10.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Saja%20AlMadinah%20Hotel17.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Saja%20AlMadinah%20Hotel1.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Saja%20AlMadinah%20Hotel5.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Saja%20AlMadinah%20Hotel13.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Saja%20AlMadinah%20Hotel14.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Saja%20AlMadinah%20Hotel15.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Saja%20AlMadinah%20Hotel16.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Saja%20AlMadinah%20Hotel.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Saja%20AlMadinah%20Hotel11.jpg",
            "https://www.hajjumrahhub.co.uk/media/hotel/Saja%20AlMadinah%20Hotel2.jpg"
        ],
        "stars": null,
        "has_wifi": true,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": 3,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/safamarwahtravel/hajj/ideal.json
{
    "url": "https://www.safamarwahtravel.co.uk/deals/3-star-21-days-shifting-hajj-package/",
    "company": "safamarwahtravel",
    "ppp": 8323,
    "year": 2026,
    "total_days": 21,
    "tier": null,
    "stars": 3,
    "departure_city": "London",
    "is_visa_included": true,
    "is_shifting": true,
    "makkah_hotel": {
        "total_days": 14,
        "name": "Nada Al Majd Hotel",
        "images": [
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/4690433411.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/1862384711.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/4690433921.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/537212357.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/469043438.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/469043420.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/469043448.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/469043407.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/469043392.jpg"
        ],
        "stars": 3,
        "has_wifi": true,
        "has_ac": true,
        "distance_to_haram": null,
        "walk_to_haram": 11,
        "number_of_beds": 4
    },
    "madinah_hotel": {
        "total_days": 7,
        "name": "Diyar Al-Madina Hotel",
        "images": [
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/2838304_17092615080056808427.webp",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/2838304_17092615110056808647.webp",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/2838304_17092615110056808645.webp",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/2838304_17092615110056808607.webp",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/2838304_17092615110056808599.webp",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/2838304_17092615110056808622.webp",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/2838304_17092615110056808624.webp",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/2838304_17092615110056808625.webp",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/2838304_17092615110056808628.jpg"
        ],
        "stars": 3,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": 10,
        "number_of_beds": 4
    }
}

=== samirm-git/hajjscanner/tests/data/aqdastravel/hajj/expected.json
{
    "url": "https://aqdastravel.co.uk/package/21-days-non-shifting-hajj-package/",
    "company": "aqdastravel",
    "ppp": null,
    "year": null,
    "total_days": 21,
    "tier": "economy",
    "stars": 3,
    "departure_city": "Manchester",
    "is_visa_included": false,
    "is_shifting": false,
    "makkah_hotel": {
        "total_days": null,
        "name": "voco Makkah",
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": null,
        "name": "Nusk Al-Madinah Hotel",
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}
