=== samirm-git/hajjscanner/schema/hajjPackage.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "hajjPackage.json",
  "title": "Package",
  "description": "Hajj package details",
  "type": "object",
  "properties": {
    "company":{
    "description": "company name",
    "type": "string"
    },
    "url":{
      "description": "url to package details",
      "type": "string",
      "format": "uri"
    },
    "ppp" : {
      "description": "price per person in £", 
      "type": ["integer", "null"],
      "minimum": 2000,
      "maximum": 25000,
      "minItems": 1
      },
    "year":{
      "description": "year in which package is offered",
      "type": ["integer", "null"],
      "minimum": 2020
    },
    "total_days":{
      "description": "total number of days in package",
      "type": ["integer", "null"],
      "minimum": 10,
      "maximum": 30
    },
    "tier":{
      "description": "type of hajj package: luxury, premium, or economy",
      "type": ["string", "null"],
      "enum": ["luxury", "premium", "economy", null]
    },
    "stars":{
      "description": "star rating (1-5)",
      "type": ["integer", "null"],
      "minimum": 1,
      "maximum": 5
    },
    "is_shifting":{
      "description": "True if shifting package, False if non shifting",
      "type": ["boolean", "null"]
    },
    "departure_city":{
      "description": "The deparature city where the umrah is being offered from.",
      "type": ["string", "null"]
    },
    "is_visa_included":{
      "description": "True if visa included in package, False if visa not included",
      "type": ["boolean", "null"]
    },

    "makkah_hotel": {
      "description": "Makkah hotel details",
      "$ref": "hotel.json"
    },
    "madinah_hotel":{
      "description": "Madinah hotel details",
      "$ref": "hotel.json"
    }
  },
  "required": ["company","ppp", "year", "total_days", "stars", "is_shifting", "departure_city", "is_visa_included", "makkah_hotel", "madinah_hotel"]
}

=== samirm-git/hajjscanner/tests/data/makkahtour/hajj/ideal.json
{
    "url": "https://www.makkahtour.co.uk/blogs/get-the-cheapest-hajj-and-umrah-packages-from-uk-best-umrah-travel-agency/",
    "company": "makkahtour",
    "ppp": null,
    "year": null,
    "total_days": null,
    "tier": null,
    "stars": null,
    "departure_city": null,
    "is_visa_included": false,
    "is_shifting": null,
    "makkah_hotel": null,
    "madinah_hotel": null
}

=== samirm-git/hajjscanner/tests/data/ihramtravel/hajj/ideal.json
{
    "url": "https://ihramtravel.co.uk/hajj-packages/",
    "company": "ihramtravel",
    "ppp": null,
    "year": 2026,
    "total_days": null,
    "tier": null,
    "stars": null,
    "departure_city": null,
    "is_visa_included": true,
    "is_shifting": null,
    "makkah_hotel": {
        "total_days": null,
        "name": null,
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": null,
        "name": null,
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/islamictravel/hajj/ideal.json
{
    "url": "https://www.islamictravel.co.uk/hajj/4-weeks-hajj-package-non-shifting.html",
    "company": "islamictravel",
    "ppp": 7195,
    "year": 2027,
    "total_days": 21,
    "tier": null,
    "stars": 3,
    "departure_city": "London Heathrow",
    "is_visa_included": true,
    "is_shifting": false,
    "makkah_hotel": {
        "total_days": 9,
        "name": "Dar Al-Sultan Hotel",
        "images": [
            "https://www.islamictravel.co.uk/media/hotel/Dar%20Al%20Sultan13.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Dar%20Al%20Sultan1.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Dar%20Al%20Sultan5.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Dar%20Al%20Sultan8.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Dar%20Al%20Sultan.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Dar%20Al%20Sultan3.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Dar%20Al%20Sultan2.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Dar%20Al%20Sultan14.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Dar%20Al%20Sultan16.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Dar%20Al%20Sultan7.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Dar%20Al%20Sultan10.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Dar%20Al%20Sultan15.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Dar%20Al%20Sultan4.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Dar%20Al%20Sultan17.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Dar%20Al%20Sultan18.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Dar%20Al%20Sultan12.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Dar%20Al%20Sultan6.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Dar%20Al%20Sultan9.jpg"
        ],
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 5,
        "name": "Al Safwa Tower Hotel",
        "images": [
            "https://www.islamictravel.co.uk/media/hotel/Al%20Safwa%20Tower5.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Al%20Safwa%20Tower14.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Al%20Safwa%20Tower3.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Al%20Safwa%20Tower12.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Al%20Safwa%20Tower7.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Al%20Safwa%20Tower16.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Al%20Safwa%20Tower.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Al%20Safwa%20Tower2.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Al%20Safwa%20Tower4.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Al%20Safwa%20Tower6.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Al%20Safwa%20Tower11.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Al%20Safwa%20Tower1.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Al%20Safwa%20Tower8.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Al%20Safwa%20Tower15.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Al%20Safwa%20Tower10.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Al%20Safwa%20Tower9.jpg"
        ],
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/hajitours/hajj/expected.json
{
    "url": "https://hajitours.com/package-category/hajj-packages/",
    "company": "hajitours",
    "ppp": null,
    "year": null,
    "total_days": null,
    "tier": null,
    "stars": null,
    "departure_city": null,
    "is_visa_included": false,
    "is_shifting": false,
    "makkah_hotel": null,
    "madinah_hotel": null
}

=== samirm-git/hajjscanner/tests/data/zamzamtravels/hajj/ideal.json
{
    "url": "https://www.zamzamtravels.org.uk/hajj-packages-2022-uk/5-star-late-hajj-package-2022-uk-two-weeks-non-shifting",
    "company": "zamzamtravels",
    "ppp": null,
    "year": 2022,
    "total_days": 15,
    "tier": null,
    "stars": 5,
    "departure_city": "London Heathrow",
    "is_visa_included": true,
    "is_shifting": false,
    "makkah_hotel": {
        "total_days": 4,
        "name": "Elaf Kinda Hotel",
        "images": [
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/elaf-kinda/68828349.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/elaf-kinda/68828356.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/elaf-kinda/68828374.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/elaf-kinda/68828377.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/elaf-kinda/68828386.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/elaf-kinda/68828365.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/elaf-kinda/68828388.jpg"
        ],
        "stars": 5,
        "has_wifi": true,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 2,
        "name": "Anwar Al-Madinah Movenpick Hotel",
        "images": [
            "https://cdn.zamzamtravels.org.uk/images/hotels/medinah/shaza-al-madina/19731930.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/medinah/shaza-al-madina/45329391.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/medinah/shaza-al-madina/19731927.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/medinah/shaza-al-madina/19731918.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/medinah/shaza-al-madina/45329372.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/medinah/shaza-al-madina/45331319.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/medinah/shaza-al-madina/45331151.jpg"
        ],
        "stars": 5,
        "has_wifi": true,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/labbaikhajjumrah/hajj/expected.json
{
    "url": "https://www.labbaikhajjumrah.co.uk/packages/shifting-hajj-package/",
    "company": "labbaikhajjumrah",
    "ppp": null,
    "year": 2027,
    "total_days": null,
    "tier": "economy",
    "stars": null,
    "departure_city": null,
    "is_visa_included": true,
    "is_shifting": false,
    "makkah_hotel": {
        "total_days": null,
        "name": "Emaar Al Khalil Hotel",
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": null,
        "name": "Mirage Al Salam Hotel",
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/alamanahtravel/hajj/ideal.json
{
    "url": "https://alamanahtravel.co.uk/27-days-economy-hajj-package/",
    "company": "alamanahtravel",
    "ppp": 4700,
    "year": 2026,
    "total_days": 27,
    "tier": "economy",
    "stars": null,
    "departure_city": null,
    "is_visa_included": true,
    "is_shifting": true,
    "makkah_hotel": {
        "total_days": 10,
        "name": "Wahet Al Deafah Hotel",
        "images": [
            "http://alamanahtravel.co.uk/wp-content/uploads/2025/09/Wahet-Al-Deafah-Hotel-1.webp",
            "http://alamanahtravel.co.uk/wp-content/uploads/2025/09/Wahet-Al-Deafah-Hotel-room-1.webp"
        ],
        "stars": null,
        "has_wifi": true,
        "has_ac": true,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 17,
        "name": "Manazil Al Aswaf",
        "images": [
            "http://alamanahtravel.co.uk/wp-content/uploads/2025/09/Manazel-Alaswaf-Hotel-2.webp",
            "http://alamanahtravel.co.uk/wp-content/uploads/2025/09/Manazel-Alaswaf-3.webp"
        ],
        "stars": null,
        "has_wifi": true,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": 5,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/zaitoontravel/hajj/expected.json
{
    "url": "https://www.zaitoontravel.co.uk/deal/21-days-non-shifting-hajj-package/",
    "company": "zaitoontravel",
    "ppp": 7885,
    "year": null,
    "total_days": 21,
    "tier": null,
    "stars": null,
    "departure_city": "Birmingham",
    "is_visa_included": true,
    "is_shifting": false,
    "makkah_hotel": {
        "total_days": null,
        "name": "Sheraton Makkah - Jabal Al Kaaba Hotel",
        "images": [
            "https://www.zaitoontravel.co.uk/theme/hotel_images/365327199.jpg",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/Sheraton_Makkah_Jabal_Al_Kaaba_Hotel_5.webp",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/Sheraton_Makkah_Jabal_Al_Kaaba_Hotel_9.webp",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/Sheraton_Makkah_Jabal_Al_Kaaba_Hotel_12.webp",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/Sheraton_Makkah_Jabal_Al_Kaaba_Hotel_11.webp",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/Sheraton_Makkah_Jabal_Al_Kaaba_Hotel_6.webp",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/Sheraton_Makkah_Jabal_Al_Kaaba_Hotel_14.webp",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/Sheraton_Makkah_Jabal_Al_Kaaba_Hotel_10.webp",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/Sheraton_Makkah_Jabal_Al_Kaaba_Hotel_8.webp",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/Sheraton_Makkah_Jabal_Al_Kaaba_Hotel_4.webp",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/Sheraton_Makkah_Jabal_Al_Kaaba_Hotel_15.webp"
        ],
        "stars": null,
        "has_wifi": true,
        "has_ac": true,
        "distance_to_haram": 1000,
        "walk_to_haram": 15,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": null,
        "name": "Al-Aqeeq Al-Madinah Hotel",
        "images": [
            "https://www.zaitoontravel.co.uk/theme/hotel_images/522052147.jpg",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/522058552.jpg",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/522056930.jpg",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/522054724.jpg",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/522052938.jpg",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/522054111.jpg",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/522054739.jpg",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/522054681.jpg",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/522055140.jpg",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/522052148.jpg",
            "https://www.zaitoontravel.co.uk/theme/hotel_images/522052725.jpg"
        ],
        "stars": null,
        "has_wifi": true,
        "has_ac": true,
        "distance_to_haram": 3000,
        "walk_to_haram": 15,
        "number_of_beds": null
    }
}
