=== samirm-git/hajjscanner/pageScraper/schema/umrahPackage.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "umrahPackage.json",
  "title": "Package",
  "description": "Umrah package details",
  "type": "object",
  "properties": {
    "company":{
    "description": "company name",
    "type": "string"
    },
    "url":{
      "description": "url to package details",
      "type": "string",
      "format": "uri"
    },
    "ppp" : {
      "description": "price per person in £", 
      "type": ["integer", "null"],
      "minimum": 100,
      "maximum": 10000,
      "minItems": 1
      },
    "year":{
      "description": "year in which package is offered",
      "type": ["integer", "null"],
      "minimum": 2020
    },
    "season":{
      "description": "season when the package is offered",
      "type": ["string", "null"],
      "enum": ["Winter", "Spring", "Summer", "Autumn", null]
    },
    "month":{
      "description": "month in which the package is offered",
      "type": ["string", "null"],
      "enum": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", null]
    },
    "islamic_month":{
      "description": "islamic month in which package is offered",
      "type": ["string", "null"],
      "enum": ["Muharram", "Safar", "Rabi' al-Awwal", "Rabi' al-Thani", "Jumada al-Ula", "Jumada al-Akhirah", "Rajab", "Sha'ban", "Ramadan", "Shawwal", "Dhu al-Qa'dah", "Dhu al-Hijjah", null]
    },
    "total_days":{
      "description": "total number of days in package",
      "type": ["integer", "null"],
      "minimum": 5,
      "maximum": 30
    },
    "tier":{
      "description": "type of hajj package: luxury, premium, or economy",
      "type": ["string", "null"],
      "enum": ["luxury", "premium", "economy", null]
    },
    "stars":{
      "description": "star rating (1-5)",
      "type": ["integer", "null"],
      "minimum": 1,
      "maximum": 5,
      "minItems": 1
    },
    "departure_city":{
      "description": "The deparature city where the umrah is being offered from.",
      "type": ["string", "null"]
    },
    "is_visa_included":{
      "description": "True if visa included in package, False if visa not included",
      "type": ["boolean", "null"]
    },
    "is_ziyarat_included":{
      "description": "Is guided tours of religious sites included in the package",
      "type": ["boolean", "null"]
    },
    "makkah_hotel": {
      "description": "Makkah hotel details",
      "$ref": "hotel.json"
    },
    "madinah_hotel":{
      "description": "Madinah hotel details",
      "$ref": "hotel.json"
    }
  },
  "required": ["company","ppp", "year", "season", "month", "islamic_month", "total_days", "stars", "departure_city", "is_visa_included", "is_ziyarat_included", "makkah_hotel", "madinah_hotel"]
}

=== samirm-git/hajjscanner/tests/data/islamictravel/umrah/expected.json
{
    "url": "https://www.islamictravel.co.uk/umrah/14-nights-5-star-easter-umrah-package.html",
    "company": "islamictravel",
    "ppp": 979,
    "year": 2026,
    "total_days": 14,
    "tier": null,
    "stars": 5,
    "departure_city": "Manchester",
    "is_visa_included": true,
    "is_ziyarat_included": false,
    "season": "Winter",
    "month": "December",
    "islamic_month": "Ramadan",
    "makkah_hotel": {
        "total_days": 7,
        "name": "Swissotel Makkah",
        "images": [
            "https://www.islamictravel.co.uk/media/hotel/Swissotel%20Makkah03.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Swissotel%20Makkah02.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Swissotel%20Makkah01.jpg"
        ],
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 7,
        "name": "Millennium Al Aqeeq Hotel",
        "images": [
            "https://www.islamictravel.co.uk/media/hotel/Millennium-Taiba-Madinah-3%20%281%29.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Saraya-Taba-Hotel-2%20%281%29.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Makarim-Umm-Al-Qura-Hotel-2%20%281%29.jpg"
        ],
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/islamictravel/umrah/ideal.json
{
    "url": "https://www.islamictravel.co.uk/umrah/14-nights-5-star-easter-umrah-package.html",
    "company": "islamictravel",
    "ppp": 979,
    "year": null,
    "total_days": 14,
    "tier": null,
    "stars": 5,
    "departure_city": "London Heathrow",
    "is_visa_included": true,
    "is_ziyarat_included": false,
    "season": "Spring",
    "month": null,
    "islamic_month": null,
    "makkah_hotel": {
        "total_days": 7,
        "name": "Swissotel Makkah",
        "images": [
            "https://www.islamictravel.co.uk/media/hotel/Swissotel%20Makkah03.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Swissotel%20Makkah02.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Swissotel%20Makkah01.jpg"
        ],
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 7,
        "name": "Al-Aqeeq Al-Madinah Hotel",
        "images": [
            "https://www.islamictravel.co.uk/media/hotel/Millennium-Taiba-Madinah-3%20%281%29.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Saraya-Taba-Hotel-2%20%281%29.jpg",
            "https://www.islamictravel.co.uk/media/hotel/Makarim-Umm-Al-Qura-Hotel-2%20%281%29.jpg"
        ],
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/sarainternationaltravel/umrah/ideal.json
{
    "url": "https://sarainternationaltravel.com/umrah-packages-in-april/",
    "company": "sarainternationaltravel",
    "ppp": 2174,
    "year": 2026,
    "total_days": null,
    "tier": "luxury",
    "stars": 5,
    "departure_city": null,
    "is_visa_included": true,
    "is_ziyarat_included": true,
    "season": "Spring",
    "month": "April",
    "islamic_month": "Shawwal",
    "makkah_hotel": {
        "total_days": null,
        "name": null,
        "images": null,
        "stars": 5,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": null,
        "name": null,
        "images": null,
        "stars": 5,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/aqdastravel/umrah/expected.json
{
    "url": "https://aqdastravel.co.uk/elderly-senior-umrah-packages/",
    "company": "aqdastravel",
    "ppp": 1299,
    "year": 2026,
    "total_days": 7,
    "tier": "premium",
    "stars": 5,
    "departure_city": "Manchester",
    "is_visa_included": true,
    "is_ziyarat_included": true,
    "season": "Summer",
    "month": "October",
    "islamic_month": "Ramadan",
    "makkah_hotel": null,
    "madinah_hotel": {
        "total_days": null,
        "name": null,
        "images": [
            "https://aqdastravel.co.uk/wp-content/uploads/2025/10/saudi-arabia-1-scaled.jpg"
        ],
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/bismillahtravel/umrah/ideal.json
{
    "url": "https://www.bismillahtravel.co.uk/umrah/3-star-7-nights-umrah-package.html",
    "company": "bismillahtravel",
    "ppp": 569,
    "year": null,
    "total_days": 7,
    "tier": null,
    "stars": 3,
    "departure_city": null,
    "is_visa_included": true,
    "is_ziyarat_included": false,
    "season": null,
    "month": null,
    "islamic_month": null,
    "makkah_hotel": {
        "name": "Al Kiswah Tower",
        "total_days": null,
        "images": [
            "https://www.bismillahtravel.co.uk/media/umrah/0ee41f0c_11zon_11zon%20%281%29.webp",
            "https://www.bismillahtravel.co.uk/media/umrah/01bfed16_11zon%20%281%29.webp",
            "https://www.bismillahtravel.co.uk/media/umrah/01cd4215_11zon_11zon.webp",
            "https://www.bismillahtravel.co.uk/media/umrah/1ead7b9f_11zon_11zon.webp",
            "https://www.bismillahtravel.co.uk/media/umrah/1540f0d8_11zon_11zon%20%281%29.webp",
            "https://www.bismillahtravel.co.uk/media/umrah/a5471220_11zon_11zon.webp",
            "https://www.bismillahtravel.co.uk/media/umrah/bea08f29_11zon_11zon.webp",
            "https://www.bismillahtravel.co.uk/media/umrah/c0a51a9e_11zon_11zon%20%281%29.webp"
        ],
        "stars": 3,
        "has_wifi": true,
        "has_ac": false,
        "other_amenities": "Dining halls, 24/7 room service, attached bathroom in every room, shuttle/transport service available at low cost.",
        "distance_to_haram": null,
        "walk_to_haram": 10,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "name": "Dar Al Eiman Al Nour",
        "total_days": null,
        "images": [
            "https://www.bismillahtravel.co.uk/media/umrah/9b680474_11zon.webp",
            "https://www.bismillahtravel.co.uk/media/umrah/b831582a_11zon_11zon.webp",
            "https://www.bismillahtravel.co.uk/media/umrah/bd3ee7d9_11zon.webp",
            "https://www.bismillahtravel.co.uk/media/umrah/c2e59211_11zon.webp",
            "https://www.bismillahtravel.co.uk/media/umrah/c658d68e_11zon.webp",
            "https://www.bismillahtravel.co.uk/media/umrah/cf7010b4_11zon.webp",
            "https://www.bismillahtravel.co.uk/media/umrah/d8c47c9c_11zon.webp",
            "https://www.bismillahtravel.co.uk/media/umrah/d289234f_11zon.webp"
        ],
        "stars": 3,
        "has_wifi": false,
        "has_ac": false,
        "other_amenities": "Furnished rooms with attached bathroom, shuttle/transport service at low cost, complimentary parking; no complimentary breakfast included; near Jannat Ul Baqi Graveyard (~5 min walk).",
        "distance_to_haram": null,
        "walk_to_haram": 3,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/alamanahtravel/umrah/expected.json
{
    "url": "https://alamanahtravel.co.uk/sic/7-nights-5-star-umrah-packages/",
    "company": "alamanahtravel",
    "ppp": 710,
    "year": 2026,
    "total_days": 7,
    "tier": "luxury",
    "stars": 5,
    "departure_city": null,
    "is_visa_included": true,
    "is_ziyarat_included": true,
    "season": null,
    "month": null,
    "islamic_month": null,
    "makkah_hotel": {
        "total_days": 4,
        "name": "Fairmont Makkah Clock Royal Tower",
        "images": null,
        "stars": 5,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 3,
        "name": "Anwar Al-Madinah Movenpick Hotel",
        "images": null,
        "stars": 5,
        "has_wifi": true,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/kiswahtravels/umrah/ideal.json
{
    "url": "https://kiswahtravels.co.uk/umrah-package/5-star-7-nights-easter-umrah-package/",
    "company": "kiswahtravels",
    "ppp": 935,
    "year": 2026,
    "total_days": 7,
    "tier": null,
    "stars": 5,
    "departure_city": null,
    "is_visa_included": true,
    "is_ziyarat_included": false,
    "season": "Spring",
    "month": null,
    "islamic_month": null,
    "makkah_hotel": {
        "name": "Al Safwah Royale Orchid",
        "total_days": 4,
        "images": [
            "https://kiswahtravels.co.uk/wp-content/uploads/elementor/thumbs/2861bd99-rbuu5vrr9rsd31xke5yt5yis944jyljjl94icy2x40.avif"
        ],
        "stars": 5,
        "has_wifi": false,
        "has_ac": false,
        "other_amenities": "Minibars, prayer rugs, luxury bathrooms, multiple restaurants, a cafe, 24-hour room service, family-friendly facilities, multilingual front desk, and accessibility options",
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "name": "ZamZam Pullman Madinah",
        "total_days": 3,
        "images": [
            "https://kiswahtravels.co.uk/wp-content/uploads/elementor/thumbs/maxresdefault-68bf4f7ae6b9f-rbh1uxw79daj6anss2yizmakn005y50x43thx5km5c.webp"
        ],
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "other_amenities": "Over 800 rooms and suites, modern and spacious, with some rooms offering views of the Haram or the Green Dome; blend of Arabic and French design",
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/taqwatours/umrah/ideal.json
{
    "url": "https://taqwatours.co.uk/5-star-umrah-package-london/",
    "company": "taqwatours",
    "ppp": 875,
    "year": null,
    "total_days": 7,
    "tier": "premium",
    "stars": 5,
    "departure_city": "London",
    "is_visa_included": true,
    "is_ziyarat_included": false,
    "season": null,
    "month": null,
    "islamic_month": null,
    "makkah_hotel": {
        "total_days": null,
        "name": "Makarem Ajyad Makkah Hotel",
        "images": [
            "https://taqwatours.co.uk/wp-content/uploads/2025/07/MAKAREM-AJYAD-MAKKAH-HOTEL.webp",
            "https://taqwatours.co.uk/wp-content/uploads/2025/07/MAKAREM-AJYAD-MAKKAH-premium-room-HOTEL.webp",
            "https://taqwatours.co.uk/wp-content/uploads/2025/07/MAKAREM-AJYAD-MAKKAH-luxury-room-HOTEL.webp",
            "https://taqwatours.co.uk/wp-content/uploads/2025/07/MAKAREM-AJYAD-MAKKAH-Best-room-HOTEL.webp"
        ],
        "stars": 5,
        "has_wifi": true,
        "has_ac": true,
        "other_amenities": "Wheelchair accessible; daily housekeeping; on-site restaurant with buffet options; 24/7 room service; city or Haram view rooms (subject to availability); elevators; in-room safe and mini fridge; tea/coffee making facilities.",
        "distance_to_haram": null,
        "walk_to_haram": 5,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": null,
        "name": "Crowne Plaza Madinah",
        "images": [
            "https://taqwatours.co.uk/wp-content/uploads/2025/07/CROWNE-PLAZA-HOTEL.webp",
            "https://taqwatours.co.uk/wp-content/uploads/2025/07/CROWNE-PLAZA-premium-room-HOTEL.webp",
            "https://taqwatours.co.uk/wp-content/uploads/2025/07/CROWNE-PLAZA-luxury-room-HOTEL.webp",
            "https://taqwatours.co.uk/wp-content/uploads/2025/07/CROWNE-PLAZA-Best-Room-HOTEL.webp"
        ],
        "stars": 5,
        "has_wifi": true,
        "has_ac": true,
        "other_amenities": "Wheelchair accessible; daily housekeeping; on-site restaurant with buffet options; 24/7 room service; city or Haram view rooms (subject to availability); elevators; in-room safe and mini fridge; tea/coffee making facilities.",
        "distance_to_haram": null,
        "walk_to_haram": 5,
        "number_of_beds": null
    }
}
