=== samirm-git/hajjscanner/pageScraper/schema/umrahPackage.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "umrahPackage.json",
  "title": "Package",
  "description": "Umrah package details",
  "type": "object",
  "properties": {
    "company":{
    "description": "company name",
    "type": "string"
    },
    "url":{
      "description": "url to package details",
      "type": "string",
      "format": "uri"
    },
    "ppp" : {
      "description": "price per person in £", 
      "type": ["integer", "null"],
      "minimum": 100,
      "maximum": 10000,
      "minItems": 1
      },
    "year":{
      "description": "year in which package is offered",
      "type": ["integer", "null"],
      "minimum": 2020
    },
    "season":{
      "description": "season when the package is offered",
      "type": ["string", "null"],
      "enum": ["Winter", "Spring", "Summer", "Autumn", null]
    },
    "month":{
      "description": "month in which the package is offered",
      "type": ["string", "null"],
      "enum": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", null]
    },
    "islamic_month":{
      "description": "islamic month in which package is offered",
      "type": ["string", "null"],
      "enum": ["Muharram", "Safar", "Rabi' al-Awwal", "Rabi' al-Thani", "Jumada al-Ula", "Jumada al-Akhirah", "Rajab", "Sha'ban", "Ramadan", "Shawwal", "Dhu al-Qa'dah", "Dhu al-Hijjah", null]
    },
    "total_days":{
      "description": "total number of days in package",
      "type": ["integer", "null"],
      "minimum": 5,
      "maximum": 30
    },
    "tier":{
      "description": "type of hajj package: luxury, premium, or economy",
      "type": ["string", "null"],
      "enum": ["luxury", "premium", "economy", null]
    },
    "stars":{
      "description": "star rating (1-5)",
      "type": ["integer", "null"],
      "minimum": 1,
      "maximum": 5,
      "minItems": 1
    },
    "departure_city":{
      "description": "The deparature city where the umrah is being offered from.",
      "type": ["string", "null"]
    },
    "is_visa_included":{
      "description": "True if visa included in package, False if visa not included",
      "type": ["boolean", "null"]
    },
    "is_ziyarat_included":{
      "description": "Is guided tours of religious sites included in the package",
      "type": ["boolean", "null"]
    },
    "makkah_hotel": {
      "description": "Makkah hotel details",
      "$ref": "hotel.json"
    },
    "madinah_hotel":{
      "description": "Madinah hotel details",
      "$ref": "hotel.json"
    }
  },
  "required": ["company","ppp", "year", "season", "month", "islamic_month", "total_days", "stars", "departure_city", "is_visa_included", "is_ziyarat_included", "makkah_hotel", "madinah_hotel"]
}

=== samirm-git/hajjscanner/tests/data/alhaqtravel/umrah/expected.json
{
    "url": "https://www.alhaqtravel.co.uk/book/conrad-makkah-all-inclusive-14-nights-umrah-package/",
    "company": "alhaqtravel",
    "ppp": 1984,
    "year": null,
    "total_days": 14,
    "tier": "premium",
    "stars": 5,
    "departure_city": "Manchester",
    "is_visa_included": true,
    "is_ziyarat_included": true,
    "season": null,
    "month": null,
    "islamic_month": null,
    "makkah_hotel": {
        "total_days": 14,
        "name": "Conrad Makkah - Jabal Omar",
        "images": [
            "https://www.alhaqtravel.co.uk/media/hotels/Conrad_Hotel_Dining_table.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/Conrad_Hotel_Counter.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/Conrad_Hotel_Hall.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/Conrad_Hotel_room.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/Conrad_Hotel_Gym.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/Conrad_Hotel_View.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/Conrad_Hotel_Bedrooms.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/Conrad_Hotel_Meeting_Area.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/Conrad_Hotel_Washroom.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/Conrad_Hotel_Rooms.jpg"
        ],
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 7,
        "name": "Maysan Al-Harithia Hotel",
        "images": [
            "https://www.alhaqtravel.co.uk/media/hotels/185528651.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/185528613.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/185528706.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/185534167.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/185528886.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/195482206.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/195482401.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/195482247.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/195482191.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/554818600.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/66593985.jpg",
            "https://www.alhaqtravel.co.uk/media/hotels/177859135.jpg"
        ],
        "stars": 5,
        "has_wifi": true,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/alhayatourstravel/umrah/expected.json
{
    "url": "https://alhayatourstravel.com/product/easter-umrah-package-2026/?add-to-cart=2549",
    "company": "alhayatourstravel",
    "ppp": 2095,
    "year": 2026,
    "total_days": null,
    "tier": null,
    "stars": null,
    "departure_city": null,
    "is_visa_included": true,
    "is_ziyarat_included": false,
    "season": "Summer",
    "month": "March",
    "islamic_month": "Ramadan",
    "makkah_hotel": {
        "total_days": null,
        "name": "Swissotel Makkah",
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": null,
        "name": "Maden Hotel",
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/zamzamtravels/umrah/ideal.json
{
    "url": "https://www.zamzamtravels.org.uk/umrah-packages-2026-uk/five-star-summer-umrah-package-from-the-uk-2026",
    "company": "zamzamtravels",
    "ppp": 1595,
    "year": 2026,
    "total_days": 11,
    "tier": "premium",
    "stars": 5,
    "departure_city": "Birmingham",
    "is_visa_included": true,
    "is_ziyarat_included": true,
    "season": "Summer",
    "month": "August",
    "islamic_month": "Safar",
    "makkah_hotel": {
        "total_days": 5,
        "name": "Swissotel Makkah",
        "images": [
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/swissotel/79949714.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/swissotel/79949634.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/swissotel/79949638.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/swissotel/79949644.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/swissotel/79949677.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/swissotel/79949683.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/makkah/swissotel/79949700.jpg"
        ],
        "stars": 5,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": 4,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 5,
        "name": "Elaf Al-Taqwa Hotel",
        "images": [
            "https://cdn.zamzamtravels.org.uk/images/hotels/madinah/elaf-al-taqwa/elaf-al-taqwa-08.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/madinah/elaf-al-taqwa/elaf-al-taqwa-02.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/madinah/mysk-touch-al-balad/359481169.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/madinah/elaf-al-taqwa/elaf-al-taqwa-03.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/madinah/elaf-al-taqwa/elaf-al-taqwa-04.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/madinah/elaf-al-taqwa/elaf-al-taqwa-05.jpg",
            "https://cdn.zamzamtravels.org.uk/images/hotels/madinah/elaf-al-taqwa/elaf-al-taqwa-06.jpg"
        ],
        "stars": 4,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/labbaikhajjumrah/umrah/ideal.json
{
    "url": "https://www.labbaikhajjumrah.co.uk/packages/10-nights-5-star-luton-umrah-package/",
    "company": "labbaikhajjumrah",
    "ppp": 1303,
    "year": null,
    "total_days": 10,
    "tier": "premium",
    "stars": 5,
    "departure_city": "London",
    "is_visa_included": false,
    "is_ziyarat_included": true,
    "season": null,
    "month": null,
    "islamic_month": null,
    "makkah_hotel": {
        "total_days": 5,
        "name": "Swissotel Makkah",
        "images": [
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2024/07/Swissotel-Hotel-Double-Room.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2024/07/Swissotel-Hotel-Kaaba-View.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2024/07/Swissotel-Hotel-Quad-Room.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2024/07/Swissotel-Hotel-Restaurant.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2024/07/Swissotel-Hotel-single-room.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2024/07/Swissotel-Hotel-Triple-Room.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2024/07/Swissotel-Hotel-TV-Lounge.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2024/07/Swissotel-Hotel-Buffet-Area.jpg"
        ],
        "stars": 5,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": 150,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 5,
        "name": "Sofitel Shahd Al Madinah Hotel",
        "images": [
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2026/02/Sofitel-Shahd-Al-Madinah-double-single-room.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2026/02/Sofitel-Shahd-Al-Madinah-hotel-double-room.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2026/02/Sofitel-Shahd-Al-Madinah-double-room.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2026/02/Sofitel-Shahd-Al-Madinah-dinning-area.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2026/02/Sofitel-Shahd-Al-Madinah-building.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2026/02/Sofitel-Shahd-Al-Madinah-bathroom.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2026/02/Sofitel-Shahd-Al-Madinah-washroom.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2026/02/Sofitel-Shahd-Al-Madinah-triple-room.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2026/02/Sofitel-Shahd-Al-Madinah-sitting-area.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2026/02/Sofitel-Shahd-Al-Madinah-reception-area.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2026/02/Sofitel-Shahd-Al-Madinah-overview.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2026/02/Sofitel-Shahd-Al-Madinah-mosque.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2026/02/Sofitel-Shahd-Al-Madinah-masjid-al-nabawi-view.jpg",
            "https://www.labbaikhajjumrah.co.uk/wp-content/uploads/2026/02/Sofitel-Shahd-Al-Madinah-hotel-sitting-area.jpg"
        ],
        "stars": 5,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": 200,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/duatravels/umrah/expected.json
{
    "url": "https://duatravels.co.uk/package/october-standard-umrah-package/",
    "company": "duatravels",
    "ppp": 1040,
    "year": null,
    "total_days": 14,
    "tier": "economy",
    "stars": 3,
    "departure_city": null,
    "is_visa_included": true,
    "is_ziyarat_included": true,
    "season": "Autumn",
    "month": "October",
    "islamic_month": null,
    "makkah_hotel": {
        "total_days": null,
        "name": null,
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": null,
        "name": null,
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/safamarwahtravel/umrah/ideal.json
{
    "url": "https://www.safamarwahtravel.co.uk/deals/5-star-10-nights-ramadan-umrah-package-from-birmingham/",
    "company": "safamarwahtravel",
    "ppp": 1721,
    "year": 2027,
    "total_days": 10,
    "tier": null,
    "stars": 5,
    "departure_city": "Birmingham",
    "is_visa_included": true,
    "is_ziyarat_included": false,
    "season": "Winter",
    "month": "February",
    "islamic_month": "Ramadan",
    "makkah_hotel": {
        "total_days": 5,
        "name": "Raffles Makkah Palace",
        "images": [
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/5366269921.webp",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/532249625.webp",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/557347537.webp",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/557347539.webp",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/550608318.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/550608315.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/557347536.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/532249746.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/532249767.jpg"
        ],
        "stars": 5,
        "has_wifi": true,
        "has_ac": true,
        "distance_to_haram": null,
        "walk_to_haram": 12,
        "number_of_beds": 4
    },
    "madinah_hotel": {
        "total_days": 5,
        "name": "Maden Hotel",
        "images": [
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/391091743.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/281430368.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/391091801.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/391099985.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/391091786.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/281429940.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/391092851.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/391092955.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/391092940.jpg"
        ],
        "stars": 5,
        "has_wifi": true,
        "has_ac": true,
        "distance_to_haram": 100,
        "walk_to_haram": 4,
        "number_of_beds": 4
    }
}

=== samirm-git/hajjscanner/tests/data/safamarwahtravel/umrah/expected.json
{
    "url": "https://www.safamarwahtravel.co.uk/deals/5-star-10-nights-ramadan-umrah-package-from-birmingham/",
    "company": "safamarwahtravel",
    "ppp": 1721,
    "year": 2027,
    "total_days": 10,
    "tier": null,
    "stars": 5,
    "departure_city": "Birmingham",
    "is_visa_included": true,
    "is_ziyarat_included": true,
    "season": "Autumn",
    "month": "September",
    "islamic_month": "Ramadan",
    "makkah_hotel": {
        "total_days": 5,
        "name": "Raffles Makkah Palace",
        "images": [
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/557347536.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/550608315.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/557347537.webp",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/557347539.webp",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/5366269921.webp",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/532249767.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/532249746.jpg",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/532249625.webp",
            "https://www.safamarwahtravel.co.uk/theme/hotel_images/550608318.jpg"
        ],
        "stars": 5,
        "has_wifi": true,
        "has_ac": true,
        "distance_to_haram": null,
        "walk_to_haram": 12,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 5,
        "name": "Maden Hotel",
        "images": null,
        "stars": 5,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": 4,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/alkhairtravel/umrah/expected.json
{
    "url": "https://www.alkhairtravel.co.uk/offer/10-nights-5-star-december-umrah-package/",
    "company": "alkhairtravel",
    "ppp": 1495,
    "year": null,
    "total_days": 10,
    "tier": "luxury",
    "stars": 5,
    "departure_city": "Manchester",
    "is_visa_included": true,
    "is_ziyarat_included": true,
    "season": "Winter",
    "month": "December",
    "islamic_month": null,
    "makkah_hotel": {
        "total_days": 5,
        "name": null,
        "images": [
            "https://www.alkhairtravel.co.uk/theme/hotels/shaza_Makkah_6.webp",
            "https://www.alkhairtravel.co.uk/theme/hotels/shaza_Makkah_8.webp",
            "https://www.alkhairtravel.co.uk/theme/hotels/shaza_Makkah_5.webp",
            "https://www.alkhairtravel.co.uk/theme/hotels/shaza_Makkah_7.webp",
            "https://www.alkhairtravel.co.uk/theme/hotels/shaza_Makkah_4.webp"
        ],
        "stars": 5,
        "has_wifi": true,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 5,
        "name": null,
        "images": [
            "https://www.alkhairtravel.co.uk/theme/hotels/5597082.jpg",
            "https://www.alkhairtravel.co.uk/theme/hotels/4788772.jpg",
            "https://www.alkhairtravel.co.uk/theme/hotels/5597123.jpg",
            "https://www.alkhairtravel.co.uk/theme/hotels/4788709.jpg",
            "https://www.alkhairtravel.co.uk/theme/hotels/4788834.jpg"
        ],
        "stars": 5,
        "has_wifi": true,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}
