=== samirm-git/hajjscanner/pageScraper/schema/umrahPackage.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "umrahPackage.json",
  "title": "Package",
  "description": "Umrah package details",
  "type": "object",
  "properties": {
    "company":{
    "description": "company name",
    "type": "string"
    },
    "url":{
      "description": "url to package details",
      "type": "string",
      "format": "uri"
    },
    "ppp" : {
      "description": "price per person in £", 
      "type": ["integer", "null"],
      "minimum": 100,
      "maximum": 10000,
      "minItems": 1
      },
    "year":{
      "description": "year in which package is offered",
      "type": ["integer", "null"],
      "minimum": 2020
    },
    "season":{
      "description": "season when the package is offered",
      "type": ["string", "null"],
      "enum": ["Winter", "Spring", "Summer", "Autumn", null]
    },
    "month":{
      "description": "month in which the package is offered",
      "type": ["string", "null"],
      "enum": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", null]
    },
    "islamic_month":{
      "description": "islamic month in which package is offered",
      "type": ["string", "null"],
      "enum": ["Muharram", "Safar", "Rabi' al-Awwal", "Rabi' al-Thani", "Jumada al-Ula", "Jumada al-Akhirah", "Rajab", "Sha'ban", "Ramadan", "Shawwal", "Dhu al-Qa'dah", "Dhu al-Hijjah", null]
    },
    "total_days":{
      "description": "total number of days in package",
      "type": ["integer", "null"],
      "minimum": 5,
      "maximum": 30
    },
    "tier":{
      "description": "type of hajj package: luxury, premium, or economy",
      "type": ["string", "null"],
      "enum": ["luxury", "premium", "economy", null]
    },
    "stars":{
      "description": "star rating (1-5)",
      "type": ["integer", "null"],
      "minimum": 1,
      "maximum": 5,
      "minItems": 1
    },
    "departure_city":{
      "description": "The deparature city where the umrah is being offered from.",
      "type": ["string", "null"]
    },
    "is_visa_included":{
      "description": "True if visa included in package, False if visa not included",
      "type": ["boolean", "null"]
    },
    "is_ziyarat_included":{
      "description": "Is guided tours of religious sites included in the package",
      "type": ["boolean", "null"]
    },
    "makkah_hotel": {
      "description": "Makkah hotel details",
      "$ref": "hotel.json"
    },
    "madinah_hotel":{
      "description": "Madinah hotel details",
      "$ref": "hotel.json"
    }
  },
  "required": ["company","ppp", "year", "season", "month", "islamic_month", "total_days", "stars", "departure_city", "is_visa_included", "is_ziyarat_included", "makkah_hotel", "madinah_hotel"]
}

=== samirm-git/hajjscanner/tests/data/ihramtravel/umrah/expected.json
{
    "url": "https://ihramtravel.co.uk/package/10-nights-5-star-glasgow-umrah-package/",
    "company": "ihramtravel",
    "ppp": 1500,
    "year": null,
    "total_days": 10,
    "tier": null,
    "stars": 5,
    "departure_city": "Glasgow",
    "is_visa_included": true,
    "is_ziyarat_included": true,
    "season": null,
    "month": null,
    "islamic_month": null,
    "makkah_hotel": {
        "total_days": 5,
        "name": null,
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 5,
        "name": "Anwar Al-Madinah Movenpick Hotel",
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/cheaphajjandumrah/umrah/expected.json
{
    "url": "https://cheaphajjandumrah.co.uk/packages/14-nights-4-star-september-umrah-package/",
    "company": "cheaphajjandumrah",
    "ppp": 384,
    "year": 2026,
    "total_days": 14,
    "tier": "economy",
    "stars": 4,
    "departure_city": "Manchester",
    "is_visa_included": false,
    "is_ziyarat_included": true,
    "season": "Autumn",
    "month": "September",
    "islamic_month": "Rabi' al-Awwal",
    "makkah_hotel": {
        "total_days": 7,
        "name": "DoubleTree by Hilton Jabal Omar Makkah",
        "images": null,
        "stars": 4,
        "has_wifi": true,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 7,
        "name": "Rawda Al Aqiq Hotel",
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": true,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/umrah-alamanah/umrah/ideal.json
{
    "url": "https://umrah-alamanah.com/wp-content/uploads/2024/10/October-Umrah-Packages--300x300.png",
    "company": "umrah-alamanah",
    "ppp": null,
    "year": null,
    "total_days": null,
    "tier": null,
    "stars": null,
    "departure_city": null,
    "is_visa_included": false,
    "is_ziyarat_included": false,
    "season": null,
    "month": null,
    "islamic_month": null,
    "makkah_hotel": null,
    "madinah_hotel": null
}

=== samirm-git/hajjscanner/tests/data/traveltoharam/umrah/ideal.json
{
    "url": "https://traveltoharam.co.uk/package/7-nights-3-star-umrah-package-2026/",
    "company": "traveltoharam",
    "ppp": 590,
    "year": 2026,
    "total_days": 7,
    "tier": "economy",
    "stars": 3,
    "departure_city": null,
    "is_visa_included": true,
    "is_ziyarat_included": true,
    "season": null,
    "month": null,
    "islamic_month": null,
    "makkah_hotel": {
        "total_days": 4,
        "name": "Almassa Grand Hotel",
        "images": null,
        "stars": 5,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 3,
        "name": "Mirage Al Salam Hotel",
        "images": null,
        "stars": 5,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/alhayatourstravel/umrah/ideal.json
{
    "url": "https://alhayatourstravel.com/product/easter-umrah-package-2026/?add-to-cart=2549",
    "company": "alhayatourstravel",
    "ppp": 2095,
    "year": 2026,
    "total_days": 15,
    "tier": null,
    "stars": 5,
    "departure_city": "Manchester",
    "is_visa_included": true,
    "is_ziyarat_included": true,
    "season": "Spring",
    "month": "March",
    "islamic_month": "Shawwal",
    "makkah_hotel": {
        "total_days": null,
        "name": "Swissotel Makkah",
        "images": null,
        "stars": 5,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": null,
        "name": "Sofitel Shahd Al Madinah Hotel",
        "images": null,
        "stars": 5,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/britishhajtravel/umrah/expected.json
{
    "url": "https://britishhajtravel.com/august-umrah-packages/",
    "company": "britishhajtravel",
    "ppp": null,
    "year": 2026,
    "total_days": null,
    "tier": "economy",
    "stars": 5,
    "departure_city": "Manchester",
    "is_visa_included": false,
    "is_ziyarat_included": false,
    "season": "Summer",
    "month": "August",
    "islamic_month": "Safar",
    "makkah_hotel": {
        "total_days": null,
        "name": null,
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": null,
        "name": null,
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/makkahtour/umrah/expected.json
{
    "url": "https://www.makkahtour.co.uk/budget-september-umrah-package-10-days.php",
    "company": "makkahtour",
    "ppp": 960,
    "year": null,
    "total_days": 10,
    "tier": null,
    "stars": 3,
    "departure_city": null,
    "is_visa_included": true,
    "is_ziyarat_included": true,
    "season": "Autumn",
    "month": "September",
    "islamic_month": null,
    "makkah_hotel": {
        "total_days": 5,
        "name": null,
        "images": [
            "https://www.makkahtour.co.uk/images/hotels/makkah/al-kiswah-tower-hotel/deluxe-bedroom.webp",
            "https://www.makkahtour.co.uk/images/hotels/makkah/al-kiswah-tower-hotel/dining-area-luxury.webp",
            "https://www.makkahtour.co.uk/images/hotels/makkah/al-kiswah-tower-hotel/lavish-bedroom.webp",
            "https://www.makkahtour.co.uk/images/hotels/makkah/al-kiswah-tower-hotel/luxury-hotel-front-view.webp",
            "https://www.makkahtour.co.uk/images/hotels/makkah/al-kiswah-tower-hotel/premium-bed.webp",
            "https://www.makkahtour.co.uk/images/hotels/makkah/al-kiswah-tower-hotel/refined-bedroom.webp",
            "https://www.makkahtour.co.uk/images/hotels/makkah/al-kiswah-tower-hotel/sophisticated-sitting-area.webp",
            "https://www.makkahtour.co.uk/images/hotels/makkah/al-kiswah-tower-hotel/sumptuous-bedroom.webp",
            "https://www.makkahtour.co.uk/images/hotels/makkah/al-kiswah-tower-hotel/upscale-bedroom.webp" 
           ],
        "stars": null,
        "has_wifi": true,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": 25,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": 5,
        "name": null,
        "images":  [
               "https://www.makkahtour.co.uk/images/hotels/madinah/swiss-international-madina/contemporary-hotel-bed-room-decor.webp",
               "https://www.makkahtour.co.uk/images/hotels/madinah/swiss-international-madina/deluxe-bedroom-suite-hotel.webp",
               "https://www.makkahtour.co.uk/images/hotels/madinah/swiss-international-madina/deluxe-room-with-king-size-bed.webp",
               "https://www.makkahtour.co.uk/images/hotels/madinah/swiss-international-madina/hotel-luxury-bed-suite.webp",
               "https://www.makkahtour.co.uk/images/hotels/madinah/swiss-international-madina/hotel-room-with-night-view.webp",
               "https://www.makkahtour.co.uk/images/hotels/madinah/swiss-international-madina/luxury-bedroom-suite-in-hotel.webp",
               "https://www.makkahtour.co.uk/images/hotels/madinah/swiss-international-madina/modern-bed-suite-in-3-star-hotel.webp",
               "https://www.makkahtour.co.uk/images/hotels/madinah/swiss-international-madina/premium-3-star-hotel-bed.webp",
               "https://www.makkahtour.co.uk/images/hotels/madinah/swiss-international-madina/spacious-luxury-bedroom-hotel.webp",
               "https://www.makkahtour.co.uk/images/hotels/madinah/swiss-international-madina/well-designed-sitting-hall-hotel.webp"
           ],
        "stars": null,
        "has_wifi": true,
        "has_ac": false,
        "distance_to_haram": 700,
        "walk_to_haram": 10,
        "number_of_beds": null
    }
}

=== samirm-git/hajjscanner/tests/data/labbaikhajjumrah/umrah/expected.json
{
    "url": "https://www.labbaikhajjumrah.co.uk/packages/10-nights-5-star-luton-umrah-package/",
    "company": "labbaikhajjumrah",
    "ppp": 1303,
    "year": null,
    "total_days": 10,
    "tier": "premium",
    "stars": 5,
    "departure_city": null,
    "is_visa_included": false,
    "is_ziyarat_included": true,
    "season": null,
    "month": null,
    "islamic_month": null,
    "makkah_hotel": {
        "total_days": null,
        "name": "Swissotel Makkah",
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    },
    "madinah_hotel": {
        "total_days": null,
        "name": "Sofitel Shahd Al Madinah Hotel",
        "images": null,
        "stars": null,
        "has_wifi": false,
        "has_ac": false,
        "distance_to_haram": null,
        "walk_to_haram": null,
        "number_of_beds": null
    }
}
